using Cinema.Models;
using DTO;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAL
{
    public class KyLuatDAL
    {
        RapPhim2Context db=new RapPhim2Context();

        public List<KyLuatDTO> GetAll()
        {
            return db.KyLuats
                .Include(x => x.MaNhanVienNavigation)
                .Select(x => new KyLuatDTO
                {
                    MaKyLuat = x.MaKyLuat,
                    MaNhanVien = x.MaNhanVien ?? 0,
                    HoTen = x.MaNhanVienNavigation.HoTen,
                    Ngay = x.Ngay.HasValue
                        ? x.Ngay.Value.ToDateTime(TimeOnly.MinValue)
                        : DateTime.Now,
                    LyDo = x.LyDo,
                    SoTienPhat = x.SoTienPhat ?? 0
                })
                .ToList();
        }

        public List<KyLuatDTO> GetByDateRange(DateOnly tuNgay, DateOnly denNgay)
        {
            return db.KyLuats
                .Include(x => x.MaNhanVienNavigation)
                .Where(x => x.Ngay.HasValue && x.Ngay.Value >= tuNgay && x.Ngay.Value <= denNgay)
                .Select(x => new KyLuatDTO
                {
                    MaKyLuat = x.MaKyLuat,
                    MaNhanVien = x.MaNhanVien ?? 0,
                    HoTen = x.MaNhanVienNavigation.HoTen,
                    Ngay = x.Ngay.HasValue
                        ? x.Ngay.Value.ToDateTime(TimeOnly.MinValue)
                        : DateTime.Now,
                    LyDo = x.LyDo,
                    SoTienPhat = x.SoTienPhat ?? 0
                })
                .ToList();
        }

        public void DeleteAutoGenerated(DateOnly ngayTinh)
        {
            var dsXoa = db.KyLuats
                .Where(x => x.Ngay == ngayTinh &&
                            (x.LyDo.StartsWith("Đi trễ ") || x.LyDo.StartsWith("Vắng/off ")))
                .ToList();

            if (dsXoa.Count == 0)
            {
                return;
            }

            db.KyLuats.RemoveRange(dsXoa);
            db.SaveChanges();
        }

        public bool Add(KyLuat kl)
        {
            db.KyLuats.Add(kl);
            db.SaveChanges();
            return true;
        }

        public bool Update(KyLuat kl)
        {
            var old = db.KyLuats.Find(kl.MaKyLuat);

            if (old == null)
                return false;

            old.MaNhanVien = kl.MaNhanVien;
            old.Ngay = kl.Ngay;
            old.LyDo = kl.LyDo;
            old.SoTienPhat = kl.SoTienPhat;

            db.SaveChanges();
            return true;
        }

        public bool Delete(int maKyLuat)
        {
            var kl = db.KyLuats.Find(maKyLuat);

            if (kl == null)
                return false;

            db.KyLuats.Remove(kl);
            db.SaveChanges();
            return true;
        }
    }
}
