using Cinema.Models;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BUS
{
    public class ThuongKyLuatBUS
    {
        private readonly ChamCongDAL chamCongDAL = new ChamCongDAL();
        private readonly KhenThuongDAL khenThuongDAL = new KhenThuongDAL();
        private readonly KyLuatDAL kyLuatDAL = new KyLuatDAL();
        public void TinhThuongKyLuat(DateOnly tuNgay, DateOnly denNgay)
        {
            khenThuongDAL.DeleteAutoGenerated(denNgay);
            kyLuatDAL.DeleteAutoGenerated(denNgay);

            var dsChamCong = chamCongDAL.GetDanhSachChamCongTheoKhoang(tuNgay, denNgay);

            var nhomTheoNhanVien = dsChamCong
                .GroupBy(x => x.MaNhanVien)
                .ToList();

            foreach (var nhom in nhomTheoNhanVien)
            {
                int maNhanVien = nhom.Key;

                int soLanTre = nhom.Count(x =>
                    x.TrangThai != null &&
                    x.TrangThai.ToLower().Contains("trễ"));

                int soLanVang = nhom.Count(x =>
                    (
                        string.Equals(x.TrangThai, "Chưa chấm công", StringComparison.OrdinalIgnoreCase) ||
                        (x.TrangThai != null &&
                            (
                                x.TrangThai.ToLower().Contains("vắng") ||
                                x.TrangThai.ToLower().Contains("off") ||
                                x.TrangThai.ToLower().Contains("nghỉ")
                            ))
                    ));

                if (soLanTre > 0)
                {
                    KyLuat kl = new KyLuat
                    {
                        MaNhanVien = maNhanVien,
                        Ngay = denNgay,
                        LyDo = $"Đi trễ {soLanTre} lần",
                        SoTienPhat = soLanTre * 100000
                    };

                    kyLuatDAL.Add(kl);
                }

                if (soLanVang > 0)
                {
                    KyLuat kl = new KyLuat
                    {
                        MaNhanVien = maNhanVien,
                        Ngay = denNgay,
                        LyDo = $"Vắng/off {soLanVang} ca",
                        SoTienPhat = soLanVang * 500000
                    };

                    kyLuatDAL.Add(kl);
                }

                if (soLanTre == 0 &&
                    soLanVang == 0 &&
                    nhom.Any())
                {
                    KhenThuong kt = new KhenThuong
                    {
                        MaNhanVien = maNhanVien,
                        Ngay = denNgay,
                        LyDo = $"Thưởng chuyên cần từ {tuNgay:dd/MM/yyyy} đến {denNgay:dd/MM/yyyy}",
                        SoTienThuong = 500000
                    };

                    khenThuongDAL.Add(kt);
                }
            }
        }
    }
}
